Repository Sarafian/MarkdownPS, pull requests merged in 2024-06, with the labels that each got.

#37 New-MDAlert commandlet and its Tests
  CHANGELOG.md
  Demo/Demo.ps1
  README.md
  Src/Modules/MarkdownPS/Public/New-MDAlert.Tests.ps1
  Src/Modules/MarkdownPS/Public/New-MDAlert.ps1
  Src/Modules/MarkdownPS/Public/New-MDQuote.ps1
Labels: enhancement

#41 39 restructure the demo section
  CI/Update-Showcase.ps1
  README.md
  Showcase/Showcase.md
  Showcase/Showcase.ps1
Labels: internal

#38 Contributing.md page
  CONTRIBUTING.md
Labels: internal

#45 Imported CI from PowerShellTemplate
  CI/Invoke-Test.ps1
  CI/Publish-Module.ps1
Labels: bug

#46 Updated MDQuote and MDAlert to address issue #43
  CHANGELOG.md
  Showcase/Showcase.md
  Src/Modules/MarkdownPS/Public/New-MDAlert.Tests.ps1
  Src/Modules/MarkdownPS/Public/New-MDAlert.ps1
  Src/Modules/MarkdownPS/Public/New-MDQuote.Tests.ps1
  Src/Modules/MarkdownPS/Public/New-MDQuote.ps1
Labels: bug

#50 Prepared 1.10 with minor corrections
  CHANGELOG.md
  CONTRIBUTING.md
  Src/Modules/MarkdownPS/MarkdownPS.psm1
Labels: internal
